FROM debian:bookworm-slim

ARG TZ=Asia/Tokyo
ENV TZ="$TZ"

RUN apt-get update && apt-get install -y --no-install-recommends \
  apache2 \
  php \
  libapache2-mod-php \
  php-cli \
  php-pgsql \
  php-mysql \
  php-curl \
  php-mbstring \
  php-xml \
  php-zip \
  && apt-get clean && rm -rf /var/lib/apt/lists/* \
  && echo "ServerName localhost" >> /etc/apache2/apache2.conf

RUN a2enmod rewrite

COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

RUN a2dissite 000-default 2>/dev/null; \
    a2ensite 000-default

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]
